version: '3.8'

services:
  postgres_orders:
    image: postgres:latest
    container_name: postgres_orders
    environment:
      POSTGRES_DB: orders_db # Maintenance database for orders
      POSTGRES_USER: myuser # Username
      POSTGRES_PASSWORD: mypassword # Password
    volumes:
      - postgres_orders_data:/var/lib/postgresql/data
    ports:
      - "5433:5432" # Host port 5433 -> Container port 5432
    restart: unless-stopped
  
  postgres_payments:
    image: postgres:latest
    container_name: postgres_payments
    environment:
      POSTGRES_DB: payments_db # Maintenance database for payments
      POSTGRES_USER: myuser # Username
      POSTGRES_PASSWORD: mypassword # Password
    volumes:
      - postgres_payments_data:/var/lib/postgresql/data
    ports:
      - "5434:5432" # Host port 5434 -> Container port 5432
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80" # <external : internal>
    depends_on:
      - postgres_orders
      - postgres_payments
    restart: unless-stopped

volumes:
  postgres_orders_data:
  postgres_payments_data: